[package]
name = "gen-music"
version = "0.1.0"
edition = "2021"

[dependencies]
rustmatica = "0.5.0"
mcdata = {version = "0.4.0",features = ["1.18","block-states","block-entities"]}
fastnbt = "2.5.0"
bounded-integer = "0.5.7"
